pipeline:
  agent:
    node:
      git branch: 'main'
      url: 'https://github.com/chihabam/meact-site.git'
      steps : 
      - npm install
      - npm run build
      - tar -czvf meact-archive.tar.gz build'''